apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deployer

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      manifest:
        type: string
        required: true

jobs:
  SVMultiLangRepo-build-artifacts-testing-jenkins:
    if: ${{ fromJSON(inputs.manifest)['SVMultiLangRepo']['build-artifacts-testing-jenkins'].deploy }}
    uses: aspm-test-qa/SVMultiLangRepo/.cloudbees/workflows/deploy.yaml
    with:
      artifact-id: ${{ fromJSON(inputs.manifest)['SVMultiLangRepo']['build-artifacts-testing-jenkins'].id }}
      environment: ${{ inputs.environment }}
